source ENV['GEM_SOURCE'] || "https://rubygems.org"

gem 'json', :require => false
gem 'ffi'
gem 'sys-filesystem'

if facterversion = ENV['FACTER_GEM_VERSION']
  gem 'facter', facterversion, :require => false
else
  gem 'facter', :require => false
end
